
'use strict';

require('dotenv').config();

const GFAPI_KEY = process.env.GFAPI_KEY;
const GFAPI_SECRET = process.env.GFAPI_SECRET;

const GfApi = require('../../index'); // require('gfapi')

// Configuración de los listados
const listings = [
{
    name: '1000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 549,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 549,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '1000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 549,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '1200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 649,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 649,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 649,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '1400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 749,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 749,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '1400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 749,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '1500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  }, 
///

{
    name: '1800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 899,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '1800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 899,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '1800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 1800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 899,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '2000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '2200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1099,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1099,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '2200 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2200 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1099,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '2400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2400 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2400 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '2600 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2600 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1299,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2600 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2600 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1299,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '2600 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2600 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1299,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '2800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1399,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1399,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '2800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 2800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1399,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '3000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '3000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '3000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '3500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '3500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '3500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1799,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '3800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '3800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '3800 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 3800 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 1999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '5000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 5000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 2599,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '5000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 5000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 2599,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '5000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 5000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 2599,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '7500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 7500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 3999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '7500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 7500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 3999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '7500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 7500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 3999,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
   {
    name: '10000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 10000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 5199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '10000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 10000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 5199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '10000 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 10000 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 5199,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
{
    name: '13500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 13500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 6499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
  {
    name: '13500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 13500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 6499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  },
    {
    name: '13500 vbucks 🎁',
    description: "!!!!! READ !!!!!\n\nNOTE: ( IT'S NOT A CODE ).\n\nNOTE 2: This is a post for 13500 V-Bucks through Gift Item Shop Method.\n\nNOTE 3: (VBUCKS CANNOT BE GIFTED).\n\nNOTE 4: (ITEM IN THE DAILY SHOP).\n\nAfter purchase, we need to be friends for at least 48 hours (2 days) in the game, and then I'll be able to send you the skins/emotes/cars/bundles that you ask me until you fulfill the amount you purchased. (Through gifting in the game)\n\nAdd me in Fortnite and send me a message about which ITEM you want.\n\nFeel free to ask any questions, and I'll answer them ASAP.\n\n✔ +2.000 satisfied customers\n\n✔ Fast delivery\n\n✔ 100% Good rating",
    price: 6499,
    status: GfApi.LISTING_STATUS.ONSALE,
    shipping_within_days: GfApi.SHIPPING_WITHIN_DAYS.THREE,
    expire_in_days: GfApi.EXPIRE_IN_DAYS.SEVEN,
    upc: "GFFORTNITE",
    category: GfApi.CATEGORY.INGAME,
    tags: ["id: Other", "type: Other", "game mode: Battle Royale","platform: Epic Games"],
    kind: GfApi.KIND.ITEM,
    digital: true,
    digital_region: 'none',
    digital_deliverable: 'transfer',
    shipping_predefined_package: 'None',
    shipping_fee: 0,
    shipping_paid_by: 'seller'
  }
];

function getImageUrl(name) {
  const imageName = name.split(' ')[0]; // Ej: '1000'

  const imageIdMap = {
    "1000": "1boOleQZSu6pGRAS56h-He3ceLiHV7jxX",
    "1200": "11hdred3Pj1bKGI0aSSsPhTHnpZbM6tIb", 
    "1400": "1m7lBRYZJM4KgYln2lGJaFzysB7kyun8c", 
    "1500": "1-BBl41l4ITd0qDOO4M7FXWlHUxdHFusx", 
    "1800": "1QTQ78vC6pdocKdscwOm2rVEr9orUyu-n", 
    "2000": "1ffZzH7EKbKL0fjDl3ApH32YyhqXr4FdD", 
    "2200": "1qncjGJAcdnpt-pytEAX4RhajeWNRlN85", 
    "2400": "1rWff0uxT3UvBmb3QLSpMbhXN9HqrgHEr", 
    "2600": "19DQWSEgmK94SVlVat7IbKopM5mir_jSc",  
    "2800": "1CGTuptY1AtFW_TvpS67aZOz5SKmwQVy7",
    "3000": "1zLZGlmCHu5CwKLRqImLNIHs7LSDoN2Zd", 
    "3500": "1Fh9Hi9-OI7N7YbQymMhoosncNEfQXkEZ", 
    "3800": "1VXta2f6tTml7_9EsekFj4rZI8NNR5eLY", 
    "5000": "1vhsnlFKri-7OlZpi5BWqN6_llR2Lo9Ue", 
    "7500": "1r_58Hti9h9-0EwtqTVweuoVsladR81_g", 
    "10000": "1mOlGbcZ0P1E2I6tHqVnBnbHtJp5j69Uh", 
    "13500": "1hsJf8gOiAJN6TF_CQkuWyaO0EnGrFTJb",  
  };

  const fileId = imageIdMap[imageName];
  if (!fileId) {
    console.warn(`No se encontró una imagen para: ${imageName}`);
    return null;
  }

  return `https://drive.google.com/uc?export=view&id=${fileId}`;
}

async function createListing(gfapi, query, delay) {
  return new Promise(resolve => {
    setTimeout(async () => {
      try {
        console.log(`Creating listing: ${query.name}`);
        let listing = await gfapi.listing_post(query);

        // Subir imágenes
let photo_url = getImageUrl(query.name);
await gfapi.upload_photo(listing.id, photo_url, 0); // Imagen de la página de listado

        // Poner el listado en venta
        await gfapi.listing_status(listing.id, GfApi.LISTING_STATUS.ONSALE);
        console.log(`Listing created and set to ON SALE: ${query.name}`);
        resolve();
      } catch (err) {
        console.error(`Error creating listing: ${query.name}`, err);
        resolve(); // Continuar con el siguiente listado aunque haya un error
      }
    }, delay);
  });
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
  const gfapi = new GfApi(GFAPI_KEY, {
    secret: GFAPI_SECRET,
    algorithm: "SHA1",
    digits: 6,
    period: 30
  }, {
    logLevel: 'debug'
  });

  while (true) {
    for (const query of listings) {
      await createListing(gfapi, query); // Publicar
      await sleep(120000); // Esperar 2 minutos antes del siguiente
    }

    console.log("🌀 Ciclo completo finalizado. Reiniciando publicaciones en 3 minutos...");
    await sleep(180000); // Esperar 1 minuto antes de empezar de nuevo
  }
}

// Run main() and catch any unhandled Promise errors
main().catch(err => {
  console.log('==== ERROR', err);
});
